services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/00_create_dbs.sql:/docker-entrypoint-initdb.d/00_create_dbs.sql:ro
      - ./db/init.sql:/docker-entrypoint-initdb.d/10_analytics.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - analytics_net

  redis:
    image: redis:7-alpine
    networks:
      - analytics_net

  redash-init:
    image: redash/redash:10.1.0.b50633
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${REDASH_DB}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      PYTHONUNBUFFERED: "0"
    command: bash -lc "python /app/manage.py database create_tables"
    networks:
      - analytics_net


  redash-server:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - redis
      - postgres
      - redash-init
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${REDASH_DB}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      PYTHONUNBUFFERED: "0"
    ports:
      - "5000:5000"
    command: server
    networks:
      - analytics_net

  redash-scheduler:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - redash-server
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${REDASH_DB}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      PYTHONUNBUFFERED: "0"
    command: scheduler
    networks:
      - analytics_net

  redash-worker:
    image: redash/redash:10.1.0.b50633
    depends_on:
      - redash-server
    environment:
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${REDASH_DB}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      QUEUES: queries,scheduled_queries,celery
      WORKERS_COUNT: 2
      PYTHONUNBUFFERED: "0"
    command: worker
    networks:
      - analytics_net

  generator:
    build: ./generator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      PLAYER_NAME: Cole_MacGrath
      PERIOD_SEC: "1"
    command: ["python", "-u", "app.py"]
    networks:
      - analytics_net


  jupyter:
    build: ./notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebook/notebooks:/home/jovyan/work/notebooks
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - analytics_net

volumes:
  pgdata:

networks:
  analytics_net:
    driver: bridge
